spring.application.name=foodapp-backend

# =====================================================
# Database Configuration
# =====================================================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ecommerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =====================================================
# JPA / Hibernate
# =====================================================

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# =====================================================
# JWT
# =====================================================

app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

app.jwt.expiration-milliseconds=${JWT_EXPIRATION:900000}

app.jwt.refresh-expiration-milliseconds=${JWT_REFRESH_EXPIRATION:604800000}


# =====================================================
# Server
# =====================================================

server.port=${PORT:8080}


# =====================================================
# Error Handling
# =====================================================

server.error.include-message=always

spring.main.allow-bean-definition-overriding=true